# Mockery v3 configuration
# https://vektra.github.io/mockery/latest/configuration/

all: false
filename: "mock_{{.InterfaceName}}.go"
recursive: false
log-level: "info"
packages:
  github.com/PromptPal/PromptPal/service:
    config:
      all: true
    interfaces:
      BaseAIService:
        config:
          all: true
      Web3Service:
        config:
          all: true
      IsomorphicAIService:
        config:
          all: true
      HashIDService:
        config:
          all: true
