// Code generated by mockery v2.42.0. DO NOT EDIT.

package service

import (
	mock "github.com/stretchr/testify/mock"
)

// MockHashIDService is an autogenerated mock type for the HashIDService type
type MockHashIDService struct {
	mock.Mock
}

// Decode provides a mock function with given fields: id
func (_m *MockHashIDService) Decode(id string) (int, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Encode provides a mock function with given fields: id
func (_m *MockHashIDService) Encode(id int) (string, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Encode")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (string, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockHashIDService creates a new instance of MockHashIDService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHashIDService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHashIDService {
	mock := &MockHashIDService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}