input openTokenInput {
  projectId: Int!
  name: String!
  description: String!
  ttl: Int!
  apiValidateEnabled: Boolean!
  apiValidatePath: String
}

type CreateOpenToken {
  token: String!
  data: openToken!
}

type openToken {
  id: Int!
  name: String!
  description: String!
  expireAt: String!
  apiValidateEnabled: Boolean!
  apiValidatePath: String!
}

type openTokenList {
  count: Int!
  edges: [openToken!]!
}
