#import * from './user.gql'
#import * from './openToken.gql'
#import * from './prompt.gql'
#import * from './call.gql'
#import * from './provider.gql'

input ProjectPayload {
  name: String
  enabled: Boolean

  openAIBaseURL: String
  openAIToken: String

  geminiBaseURL: String
  geminiToken: String

  openAIModel: String
  openAITemperature: Float
  openAITopP: Float
  openAIMaxTokens: Int

  providerId: Int!
}

type ProjectPromptMetricsRecentCount {
  prompt: Prompt!
  count: Int!
}

type ProjectPromptMetricsByDate {
  date: String!
  prompts: [ProjectPromptMetricsRecentCount!]!
}

type ProjectPromptMetrics {
  recentCounts: [ProjectPromptMetricsRecentCount!]!
  last7Days: [ProjectPromptMetricsByDate!]!
}

type Project {
  id: Int!
  name: String!
  enabled: Boolean!

  openAIBaseURL: String!
  openAIToken: String!

  geminiBaseURL: String!
  geminiToken: String!

  openAIModel: String!
  openAITemperature: Float!
  openAITopP: Float!
  openAIMaxTokens: Int!

  createdAt: String!
  updatedAt: String!
  creator: User!
  openTokens: openTokenList!
  latestPrompts: PromptList!

  promptMetrics: ProjectPromptMetrics!

  provider: Provider
}

type ProjectList {
  count: Int!
  edges: [Project!]!
}
