#import * from './user.gql'
#import * from './openToken.gql'

input ProjectPayload {
  name: String
  openAIToken: String
  enabled: Boolean
  openAIBaseURL: String
  openAIModel: String
	openAIToken: String
	openAITemperature: Float
	openAITopP: Float
	openAIMaxTokens: Int
}

type Project {
  id: Int!
  name: String!
  openAIToken: String!
  enabled: Boolean!
  openAIBaseURL: String!
  openAIModel: String!
	openAIToken: String!
	openAITemperature: Float!
	openAITopP: Float!
	openAIMaxTokens: Int!
  createdAt: String!
  updatedAt: String!
  creator: User!
  openTokens: openTokenList!
}

type ProjectList {
  count: Int!
  edges: [Project!]!
}
