#import * from './call.gql'
#import * from './user.gql'
#import * from './history.gql'
#import * from './project.gql'

enum PromptRole {
  system
  user
  assistant
}

enum PublicLevel {
  public
  protected
  private
}

input PromptRowInput {
  prompt: String!
  role: PromptRole!
}

input PromptSearchFilters {
  userId: String
}

enum PromptVariableTypes {
  string
  number
  boolean
  video
  audio
  image
}

input PromptVariableInput {
  name: String!
  type: PromptVariableTypes!
}

type PromptRow {
  prompt: String!
  role: PromptRole!
}

type PromptVariable {
  name: String!
  type: PromptVariableTypes!
}

input PromptPayload {
  projectId: Int!
  name: String!
  description: String!
  enabled: Boolean
  debug: Boolean
  tokenCount: Int!
  prompts: [PromptRowInput!]!
  variables: [PromptVariableInput!]!
  publicLevel: PublicLevel!
}

type Prompt {
  id: Int!
  hashId: String!
  name: String!
  description: String!
  enabled: Boolean!
  debug: Boolean!
  tokenCount: Int!
  prompts: [PromptRow!]!
  variables: [PromptVariable!]!
  publicLevel: PublicLevel!
  project: Project!

  createdAt: String!
  updatedAt: String!
  latestCalls: PromptCallList!
  metrics: PromptMetrics!
  creator: User!
  histories: PromptHistoryResp!
}

type PromptList {
  count: Int!
  edges: [Prompt!]!
}

type PromptMetrics {
  p50: Float!
  p90: Float!
  p99: Float!
}
