input AuthInput {
  address: String!
  signature: String!
  message: String!
}

input PasswordAuthInput {
  email: String!
  password: String!
}

type User {
  id: Int!
  name: String!
  addr: String!
  avatar: String!
  email: String!
  phone: String!
  lang: String!
  level: Int!
  source: String!
}

input CreateUserPayload {
  name: String!
  email: String!
  phone: String
  lang: String
  level: Int
  avatar: String
  username: String
}

type CreateUserResponse {
  user: User!
  password: String!
}

type Auth {
  token: String!
  user: User!
}
