#import * from './user.gql'
#import * from './project.gql'

input WebhookPayload {
  name: String!
  description: String
  url: String!
  event: String!
  enabled: Boolean
  projectId: Int!
}

input WebhookUpdatePayload {
  name: String
  description: String
  url: String
  event: String
  enabled: Boolean
}

type Webhook {
  id: Int!
  name: String!
  description: String!
  url: String!
  event: String!
  enabled: Boolean!
  createdAt: String!
  updatedAt: String!
  creator: User!
  project: Project!
}

type WebhookList {
  count: Int!
  edges: [Webhook!]!
}
