#import * from './types/project.gql'
#import * from './types/prompt.gql'
#import * from './types/openToken.gql'

schema {
  query: Query
  mutation: Mutation
}

type Query {
  project(id: Int!): Project!
}

type Mutation {
  createProject(data: ProjectPayload!): Project!
  updateProject(id: Int!, data: ProjectPayload!): Project!
  deleteProject(id: Int!): Boolean!

  createPrompt(data: PromptPayload!): Prompt!
  updatePrompt(id: Int!, data: PromptPayload!): Prompt!
  deletePrompt(id: Int!): Boolean!

  createOpenToken(data: openTokenInput!): openToken!
  deleteOpenToken(id: Int!): Boolean!
}
